In [5]:
import numpy as np
x = np.array([1, 2, 3, 5])
N = 3
np.vander(x, N)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

In [7]:
np.column_stack([x**(N-1-i) for i in range(N)])

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]], dtype=int32)

In [8]:
x = np.array([1, 2, 3, 5])
np.vander(x)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])

In [9]:
np.vander(x, increasing=True)

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   5,  25, 125]])

In [11]:
#The determinant of a square Vandermonde matrix is the product of the differences between the values of the input vector:
np.linalg.det(np.vander(x))

48.00000000000003

In [12]:
#Compare the results
(5-3)*(5-2)*(5-1)*(3-2)*(3-1)*(2-1)

48

In [13]:
# above steps combined together as follows:

import numpy as np
x = np.array([1, 2, 3, 5])
N = 3
np.vander(x, N)
np.column_stack([x**(N-1-i) for i in range(N)])
x = np.array([1, 2, 3, 5])
np.vander(x)
np.vander(x, increasing=True)
np.linalg.det(np.vander(x))
(5-3)*(5-2)*(5-1)*(3-2)*(3-1)*(2-1)

48